# Generated by Django 5.2.17 on 2026-10-08 15:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='catégorie')),
                ('is_investment', models.BooleanField(default=False, verbose_name='immobilisation')),
                ('useful_life_months', models.PositiveSmallIntegerField(default=36, validators=[django.core.validators.MinValueValidator(1)], verbose_name="durée d'amortissement (mois)")),
            ],
            options={
                'verbose_name': 'catégorie de dépense',
                'verbose_name_plural': 'catégories de dépenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom du lot')),
                ('start_date', models.DateField(verbose_name="date d'arrivée")),
                ('target_duration_days', models.PositiveSmallIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée prévue (jours)')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='poussins reçus')),
                ('unit_cost_chick', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='coût unitaire du poussin')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('closed', 'Clôturé'), ('archived', 'Archivé')], default='active', max_length=10, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
                'ordering': ['-start_date', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_duration_days__gt', 0)), name='batch_duration_positive'), models.CheckConstraint(condition=models.Q(('unit_cost_chick__gte', 0)), name='batch_chick_cost_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('starter', 'Démarrage'), ('grower', 'Croissance'), ('finisher', 'Finition')], max_length=10, verbose_name="type d'aliment")),
                ('purchase_date', models.DateField(verbose_name="date d'achat")),
                ('bags_purchased', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='sacs achetés')),
                ('bag_weight_kg', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='poids par sac (kg)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix du sac')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='fournisseur')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': "entrée de stock d'aliment",
                'verbose_name_plural': "stocks d'aliments",
                'ordering': ['-purchase_date', 'feed_type'],
                'constraints': [models.CheckConstraint(condition=models.Q(('bags_purchased__gt', 0)), name='feed_bags_positive'), models.CheckConstraint(condition=models.Q(('bag_weight_kg__gt', 0)), name='feed_bag_weight_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='feed_unit_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='ProphylaxisProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='soin / protocole')),
                ('target_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='jour cible')),
                ('duration_days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée (jours)')),
                ('frequency_days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='intervalle (jours)')),
                ('medicine_name', models.CharField(max_length=120, verbose_name='produit')),
                ('dosage', models.CharField(blank=True, max_length=120, verbose_name='dosage')),
                ('administration_route', models.CharField(default='Eau de boisson', max_length=80, verbose_name="voie d'administration")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'protocole prophylactique',
                'verbose_name_plural': 'protocoles prophylactiques',
                'ordering': ['target_day', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_day__gt', 0)), name='prophylaxis_target_day_positive'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='prophylaxis_duration_positive'), models.CheckConstraint(condition=models.Q(('frequency_days__gt', 0)), name='prophylaxis_frequency_positive')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('designation', models.CharField(max_length=180, verbose_name='désignation')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('invoice_file', models.FileField(blank=True, upload_to='invoices/%Y/%m/', verbose_name='facture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('batch', models.ForeignKey(blank=True, help_text="Laisser vide pour une dépense fixe de l'exploitation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='poulailler_core.batch', verbose_name='lot')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='poulailler_core.expensecategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-date', '-pk'],
                'indexes': [models.Index(fields=['batch', 'date'], name='poulailler__batch_i_8531a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('feed_type', models.CharField(choices=[('starter', 'Démarrage'), ('grower', 'Croissance'), ('finisher', 'Finition')], max_length=10, verbose_name="type d'aliment")),
                ('bags_consumed', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='sacs consommés')),
                ('kg_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='kilogrammes consommés')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_consumptions', to='poulailler_core.batch', verbose_name='lot')),
            ],
            options={
                'verbose_name': "consommation d'aliment",
                'verbose_name_plural': "consommations d'aliment",
                'ordering': ['-date', '-pk'],
                'indexes': [models.Index(fields=['batch', 'date'], name='poulailler__batch_i_16a55b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bags_consumed__gt', 0), ('kg_consumed__isnull', True)), models.Q(('bags_consumed__isnull', True), ('kg_consumed__gt', 0)), _connector='OR'), name='feed_consumption_one_positive_measure')],
            },
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='nombre de morts')),
                ('cause_suspected', models.CharField(choices=[('disease', 'Maladie'), ('crushing', 'Écrasement'), ('unknown', 'Inconnu'), ('other', 'Autre')], default='unknown', max_length=12, verbose_name='cause présumée')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortalities', to='poulailler_core.batch', verbose_name='lot')),
            ],
            options={
                'verbose_name': 'mortalité',
                'verbose_name_plural': 'mortalités',
                'ordering': ['-date', '-pk'],
                'indexes': [models.Index(fields=['batch', 'date'], name='poulailler__batch_i_51c20f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('count__gt', 0)), name='mortality_count_positive')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('quantity_sold', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité vendue')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='poids total (kg)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix unitaire')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant total')),
                ('customer_name', models.CharField(blank=True, max_length=160, verbose_name='client')),
                ('payment_status', models.CharField(choices=[('paid', 'Payé'), ('credit', 'Crédit / avance')], default='paid', max_length=8, verbose_name='paiement')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='poulailler_core.batch', verbose_name='lot')),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-date', '-pk'],
                'indexes': [models.Index(fields=['batch', 'date'], name='poulailler__batch_i_e98cad_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_sold__gt', 0)), name='sale_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='sale_unit_price_positive'), models.CheckConstraint(condition=models.Q(('total_amount__isnull', True), ('total_amount__gt', 0), _connector='OR'), name='sale_total_positive_or_empty')],
            },
        ),
        migrations.CreateModel(
            name='TreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="jour d'âge ciblé")),
                ('date_planned', models.DateField(verbose_name='date prévue')),
                ('date_administered', models.DateField(blank=True, null=True, verbose_name='date administrée')),
                ('medicine_name', models.CharField(max_length=120, verbose_name='médicament / soin')),
                ('dosage', models.CharField(blank=True, max_length=120, verbose_name='dosage')),
                ('administration_route', models.CharField(blank=True, max_length=80, verbose_name="voie d'administration")),
                ('is_completed', models.BooleanField(default=False, verbose_name='effectué')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='poulailler_core.batch', verbose_name='lot')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='poulailler_core.prophylaxisprogram', verbose_name='protocole')),
            ],
            options={
                'verbose_name': 'suivi de soin',
                'verbose_name_plural': 'suivis de soins',
                'ordering': ['date_planned', 'target_day', 'pk'],
                'indexes': [models.Index(fields=['batch', 'date_planned', 'is_completed'], name='poulailler__batch_i_07fd8a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_day__gt', 0)), name='treatment_target_day_positive'), models.UniqueConstraint(fields=('batch', 'program', 'target_day'), name='unique_batch_program_day')],
            },
        ),
    ]
