# Generated by Django 5.2.17 on 2026-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poulailler_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de clôture'),
        ),
    ]
