# Generated by Django 5.2.17 on 2026-10-09 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poulailler_core', '0002_batch_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bonus_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='poussins bonus / ajout (offerts)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='ordered_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='poussins commandés (facturés)'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='initial_quantity',
            field=models.PositiveIntegerField(verbose_name='effectif démarré / reçus'),
        ),
    ]
